services:
  - type: web
    name: directus-app
    env: docker
    dockerImage: directus/directus:latest
    plan: free # Change to 'starter' or higher if you need more resources
    healthCheckPath: /server/health
    envVars:
      - key: PORT
        value: 8055
      # Directus Database config (SQLite)
      - key: DB_CLIENT
        value: sqlite3
      - key: DB_FILENAME
        value: /directus/database/data.db
      # Authentication & Security tokens
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true
      # Initial Admin Credentials
      - key: ADMIN_EMAIL
        value: admin@example.com # Change this
      - key: ADMIN_PASSWORD
        sync: false # Render will prompt you to type this securely in the UI
    disk:
      name: directus-data
      mountPath: /directus/database
      sizeGB: 1
